export const queryKeys = {
  profile: ['profile'] as const,
  nutritionProvider: ['nutrition-provider'] as const,
  providerCatalog: ['nutrition-provider', 'catalog'] as const,
  providerModels: ['nutrition-provider', 'models'] as const,
  target: (date: string) => ['target', date] as const,
  dashboard: (date: string) => ['dashboard', date] as const,
  foods: (search: string) => ['foods', search] as const,
  recentFoods: ['foods', 'recent'] as const,
  foodEntries: (date: string) => ['food-entries', date] as const,
  activityTypes: ['activity-types'] as const,
  activityEntries: (date: string) => ['activity-entries', date] as const,
  recentActivities: ['activity-entries', 'recent'] as const,
  savedExercises: ['saved-exercises'] as const,
  workouts: ['workouts'] as const,
  calendar: (from: string, to: string) => ['calendar', from, to] as const,
  weight: (from?: string, to?: string) => ['weight', from ?? '', to ?? ''] as const,
  history: (from: string, to: string) => ['history', from, to] as const,
  progress: (from: string, to: string) => ['progress', from, to] as const,
};

export const DAY_SCOPED_KEYS = [
  'dashboard',
  'history',
  'progress',
  'food-entries',
  'activity-entries',
  'weight',
  'saved-exercises',
  'workouts',
  'calendar',
] as const;
